server:
  port: 8778    #default port where the service will be started
 
eureka:         #tells about the Eureka server details and its refresh time
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
  client:
    serviceUrl:
      defaultZone: http://172.17.0.1:1080/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
 
management:
  security:
    enabled: false  #disable the spring security on the management endpoints like /env, /refresh etc.
    
spring:    
  application:
    name: service1   #current service name to be used by the eureka server

        
 
